CCD-3509 CVE-2021-22044 spring-cloud-dependencies upgraded 2021.0.3, … (#426)
* CCD-3509 CVE-2021-22044 spring-cloud-dependencies upgraded 2021.0.3, spring-cloud-starter-openfeign upgraded 3.1.3, FeignException args fixed, responseBodyByteArray to string changes PrdFeignClientTest, imports fixed, suppression removed
Conflicts Resolved

* CCD-3509 CVE-2021-22044 sprint boot 2.6.10, Gradle 6.8.3

* CCD-3509 CVE-2021-22044 sprint boot 2.6.10

* CCD-3509 CVE-2021-22044 spring.mvc.pathmatch.matching-strategy = ant_path_matcher, added webEndpointServletHandlerMapping method, fixes null pointers in integration tests

* CCD-3509 CVE-2021-22044 WIP multiple changes with attempts commented out. Local healthcheck smoke test fails

* CCD-3509 CVE-2021-22044 ZuulConfiguration added to fixZuulProxyDataStoreRequestIT  Netflix Zuul - NoSuchMethodError: ErrorController.getErrorPath()

* CCD-3509 CVE-2021-22044 SwaggerConfigurationTest added for sonar coverage

* CCD-3509 CVE-2021-22044 webEndpointServletHandlerMapping removed from TestIdamConfiguration maybe not needed

* Empty-Commit

* CCD-3509 CVE-2021-22044 RequestedCaseUnassignment fields final modifier removed, @NoArgsConstructor added, previous no args constructor removed, Warning.NONFINAL_FIELDS suppressed in tests

* CCD-3509 CVE-2021-22044 added caseId to exception text for debug

* CCD-3509 CVE-2021-22044 temp change to test during debug

* CCD-3509 CVE-2021-22044 comment changed for checkstyle

* Revert "CCD-3509 CVE-2021-22044 comment changed for checkstyle"

This reverts commit 39f14652f3bf907184bf0fc59a92aa08d21a6311.

* Revert "CCD-3509 CVE-2021-22044 temp change to test during debug"

This reverts commit c16f856522978dad7df25b8ef4341c23f9d850ab.

* Revert "CCD-3509 CVE-2021-22044 added caseId to exception text for debug"

This reverts commit ff227a35e088d734f525b45722e9b3187eaff0b5.

* CCD-3509 CVE-2021-22044 attempt at changing the logging level

* CCD-3509 CVE-2021-22044 attempt at turning debug mode on

* CCD-3509 CVE-2021-22044 @JsonAlias("data") added to CaseDetails data field

* CCD-3509 CVE-2021-22044 commented out debug mode in yml, removed commented code, removed increased DEBUG logging

* CCD-3509 CVE-2021-22044 tests use constants, blank lines removed

* Dummy commit to trigger build

Co-authored-by: lucianotmarsilio <luciano.marsilio@hmcts.net>